### ISSUE TITLE
System.xml has an element which does not have an id

### ISSUE THREAD

**Issue by frostblogNet** [dotmailer/dotmailer-magento2-extension-enterprise#13] opened 2019-02-06 08:22 UTC
Hello,

we have upgraded one of our magento installations from 2.2.7 to 2.3.0. After login the configuration section in admin backend was brocken. 

Error message was 

"Notice: Undefined index: id in /.../vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63"

After some debugging I found out that there is an element which does not have an id element. 

Looks like the element is ddg_automation in your system.xml. 

dotmailer/dotmailer-magento2-extension-enterprise is 1.0.2

Would be nice if you can fix this.

Thanks in advance
Jens

**Comment by sta1r** [comment] 2019-04-04 09:18
Hello @frostblogNet and thanks for raising this.

There is no tab id defined in this module by intention, because it depends on the `ddg_automation` tab id (already defined)[https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/etc/adminhtml/system.xml#L4-L6] in its 'parent' module.

When you upgraded, were both modules enabled? Does the problem persist? Or how have you resolved it?

**Comment by frostblogNet** [comment] 2019-04-04 10:31
Hello @sta1r,

Both modules were enabled. The problem is till present also in 2.3.1. We have exculded both extensios using a replace in the composer.json. 

We use a error capture extension based on https://github.com/filp/whoops . To see such errors.

Hope this will help you.

**Comment by sta1r** [comment] 2020-01-30 10:11
We have recently had some fresh insight into why this menu problem might occur. See https://github.com/magento/magento2/issues/26573. 

In the case of both issues, a Magento upgrade has happened where a new 'child' bundled module is introduced (Dotdigitalgroup_Enterprise in 2.3.0, Dotdigitalgroup_Chat in 2.3.4) that has a dependency on a 'parent' bundled module (Dotdigitalgroup_Email). These children are dependent in many ways, one of which is that they both attach to the same menu structure. 

If the parent module is disabled at point of upgrade, and the new child module comes pre-enabled (which it evidently does), problems will occur in relation to the unresolved dependency.

Composer has all the dependency information it needs, as does module.xml. It's up to Magento to resolve these and not enable a new child if its parent is disabled. Thankfully the problem is easy to resolve by disabling the child, but of course it makes for a slightly messy upgrade.  

@frostblogNet I'm closing this now. Thanks again.

**Closed by sta1r** 2020-01-30 10:11 UTC
